### ISSUE TITLE
Chapter 3 Super Helpers

### ISSUE THREAD

**Issue by orozcorp** [Lepozepo/online_shop#1]
The app crashes after 
@Products = new Mongo.Collection "products"

if Meteor.isServer
  if Products.find().count() is 0
    Products.insert
      name:"Nuka Cola"
      price: 1099

```
Products.insert
  name:"1up Soda"
  price: 999

Products.insert
  name:"JuggerNog"
  price: 899
```

this is the error

W20151105-16:12:00.278(-6)? (STDERR)          

W20151105-16:12:00.278(-6)? (STDERR) /Users/ObookPro/.meteor/packages/meteor-tool/.1.1.10.4nyfu9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245

W20151105-16:12:00.278(-6)? (STDERR) throw(ex);

W20151105-16:12:00.279(-6)? (STDERR)       ^

W20151105-16:12:00.387(-6)? (STDERR) Error: A method named '/products/insert' is already defined

W20151105-16:12:00.387(-6)? (STDERR)     at livedata_server.js:1542:15

W20151105-16:12:00.387(-6)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)

W20151105-16:12:00.387(-6)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)

W20151105-16:12:00.387(-6)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)

W20151105-16:12:00.388(-6)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:218:1)

W20151105-16:12:00.388(-6)? (STDERR)     at products/collections/productcol.coffee:1:17

W20151105-16:12:00.388(-6)? (STDERR)     at products/collections/productcol.coffee:1:1

W20151105-16:12:00.388(-6)? (STDERR)     at /Users/ObookPro/online_shop/.meteor/local/build/programs/server/boot.js:242:10

W20151105-16:12:00.388(-6)? (STDERR)     at Array.forEach (native)

W20151105-16:12:00.389(-6)? (STDERR)     at Function._.each._.forEach (/Users/ObookPro/.meteor/packages/meteor-tool/.1.1.10.4nyfu9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)

**Comment by Lepozepo** [comment]
You're probably duplicating things. Don't forget to read your error messages!

```
W20151105-16:12:00.387(-6)? (STDERR) Error: A method named '/products/insert' is already defined
```

``` coffeescript
# /_globals/lib/collections/products/products.coffee
@Products = new Mongo.Collection "products"

# fields:
#  name
#  description
#  sku
```
